---
- name: Install fuse-utils
  apt: pkg=fuse state=present
  tags:
    - install-fuse

- name: Install goofys binary
  get_url:
    url: "https://github.com/kahing/goofys/releases/download/v0.0.6/goofys"
    dest: /usr/bin/goofys
    mode: 0777
  tags:
    - install-goofys
