---
- name: download chrome browser
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /home/ubuntu

- name: Install a chrome browser
  become: yes
  apt:
    deb: /home/ubuntu/google-chrome-stable_current_amd64.deb
