---
## Install System Pakcages and Utils

- name: dpkg --configure -a
  shell: dpkg --configure -a
  tags:
    - packages
    - common
    - dpkg-reconf

- name: install system pakcages and utils
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=5400 allow_unauthenticated=yes
  with_items:
   - openssl
   - git
   - git-core
   - golang
   - ruby-compass
   - goaccess
   - htop
   - rsyslog
   - zip
   - vim
   - vim-common
   - curl
   - multitail
   - redis-tools
   - sysvbanner
   - figlet
   - upstart
   - python-pip
   - python-software-properties
   - mysql-client
   - libfontconfig
   - chromium-browser
  tags:
    - packages
    - common

- name: install pip packages ( aws .. )
  pip: name=awscli
  tags:
    - awscli
    - common
    - packages

