---
# install pecl libraries
#
#

- name: update pecl channel
  shell: pecl update-channels
  become: true
  tags:
    - pecl-update

- name: create pecl extensions .ini files
  template: src=files/mods-available/mongodb.ini dest={{ php_dir }}/mods-available/mongodb.ini owner=root group=root mode=0644
  tags:
    - pecl-config
    - pecl-ini

- name: enable pecl extensions
  shell: phpenmod  {{ item }}
  with_items:
    #- lzf
    - mongodb
  tags:
    - pecl-config
